made api in backend and fetched in front-end, used middleware
kalviumcommunity/RentIt pull request #9
Opened 2023-03-10 12:41 UTC by a5h101

2023-03-11 18:39 UTC, a5h101 commented
I have not deleted the all console logs and comments because I will need them for some time

2023-03-13 04:16 UTC, PatelNeelMahesh requested changes
You need to add node_modules in .gitignore file and provide description for the PR.
After making the changes you can merge pull request.

2023-03-13 04:16 UTC, PatelNeelMahesh commented on Rentit-backend/app.js
> +      message: 'imvalid ID',
"invalid ID"

2023-03-13 04:16 UTC, PatelNeelMahesh commented on Rentit-frontend/src/components/items/items.jsx
> +    const url = 'http://127.0.0.1:2000/api-rentit/v1/items';
domain url, api keys and other sensitive details should be stored in .evn files and access using process.env

2023-03-13 04:55 UTC, merged